import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'

import Card from '../components/Card'

export default function Home() {

  const [count, setCount] = useState(0)
  const [todolist, setTodoList] = useState([])
  const [contener, setContener] = useState('')
  const [disabled, setDisabled] = useState(true)
  const [editabledTodo, setEditabledTodo] = useState(null)
  const [color, setColor] = useState('#fff')


  const edit = (item, index) => {
    setEditabledTodo(index)
  }

  const handleChange = e => {
    let newTodoList = [...todolist]
    newTodoList[editabledTodo] = e.target.value

    setTodoList(newTodoList)
    
  }

  useEffect(() => {
    console.log("modification")
  }, [todolist])

  useEffect(() => {
    count >= 1 && setColor('#222')
  }, [count]) 

  useEffect(() => {
    localStorage.setItem("tudos", todolist)
    return () => {
      localStorage.clear()
    }
  }, [todolist])   


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome</h1>
        <div style={{
          display : 'flex',
          justifyContent: 'space-between',
          margin: '100px'
        }}>
          <p>Marketplace</p>
          <p>Menu</p>
          <button>Login</button>
        </div>
        <div style={{
          display: 'flex',
          justifyContent: 'space-between'
        }}>
        <Card title="TITRE" desc="description" image="https://images.unsplash.com/photo-1639562471146-45adb126ed96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" price="21"/>
        <Card title="TITRE" desc="description" image="https://images.unsplash.com/photo-1639562471146-45adb126ed96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" price="21"/>
        <Card title="TITRE" desc="description" image="https://images.unsplash.com/photo-1639562471146-45adb126ed96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" price="21"/>
        <Card title="TITRE" desc="description" image="https://images.unsplash.com/photo-1639562471146-45adb126ed96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" price="21"/>
        <Card title="TITRE" desc="description" image="https://images.unsplash.com/photo-1639562471146-45adb126ed96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" price="21"/>
        <Card title="TITRE" desc="description" image="https://images.unsplash.com/photo-1639562471146-45adb126ed96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" price="21"/>
      
        </div>
        
       </main>
    </div>
  )
}
