import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react'

export default function Home() {

  const [count, setCount] = useState(0)
  const [todolist, setTodoList] = useState([])
  const [contener, setContener] = useState('')
  const [disabled, setDisabled] = useState(true)
  const [editabledTodo, setEditabledTodo] = useState(null)

  const edit = (item, index) => {
    setEditabledTodo(index)
  }

  const handleChange = e => {
    let newTodoList = [...todolist]
    newTodoList[editabledTodo] = e.target.value

    setTodoList(newTodoList)
    
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>hello</h1>
        <h3>count : {count}</h3>
        <button onClick={() => setCount(prev => prev + 1)}> click</button>

        <input type='text' value={contener} onChange={event => setContener(event.target.value)}></input>
        <button onClick={() => setTodoList(e => [...e, contener])}>Ajouter à la liste</button>


        { todolist.length > 0 && (
            todolist.map((todo, i) => {
              
              return (

                <div key={i}>
                  <input type='text' onChange={(e) => handleChange(e)} defaultValue={todo} disabled={editabledTodo === i  ? false : true}/>
                  <button onClick={() => edit(todo, i)}>Edit</button>
                  <button onClick={() => setTodoList(r => r.filter((item, index) => index !== i))}>Supprimer</button>
                </div>

              )
             
            })
          )          
        }
        
       </main>
    </div>
  )
}
